[2024-10-21 08:31:33 UTC] Step evaluate_model has started.

[2024-10-21 08:31:33 UTC] /mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:404: UserWarning: <built-in function any> is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.
  warn(

[2024-10-21 08:31:33 UTC] /mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py:255: FutureWarning: ``mlflow.gluon.autolog`` is deprecated since 2.5.0. This method will be removed in a future release.
  module.autolog(disable=True)

[2024-10-21 08:31:33 UTC] Failed to run step evaluate_model after 1 retries. Exiting.

[2024-10-21 08:31:33 UTC] Run with UUID f98abdf66f7942a594488d1efeb95b08 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
Traceback (most recent call last):
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 292, in launch
    self._run_step(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 499, in _run_step
    self._run_step_without_step_operator(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 583, in _run_step_without_step_operator
    runner.run(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_runner.py", line 198, in run
    return_values = step_instance.call_entrypoint(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/steps/base_step.py", line 692, in call_entrypoint
    return self.entrypoint(**validated_args)
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/steps/evalaute.py", line 41, in evaluate_model
    with mlflow.start_run():
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 321, in start_run
    raise Exception(
Exception: Run with UUID f98abdf66f7942a594488d1efeb95b08 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True

